# .github/workflows/deploy.yml

name: Deploy Serverless Data Pipeline

on:
  push:
    branches:
      - main # This pipeline runs when you push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Serverless Framework and Dependencies
        run: npm install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 # Set to your deployment region

      - name: Deploy to AWS
        run: npx serverless deploy --stage dev
