name: Deploy Serverless Application

on:
  push:
    branches:
      - main # Triggers the workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Change to your desired AWS region

      # If the repo uses Node.js and AWS SAM
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Deploy with AWS SAM
        run: |
          sam build
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name my-serverless-app --capabilities CAPABILITY_IAM --resolve-s3

      # If the repo uses the Serverless Framework, the deploy step would be:
      # - name: Deploy with Serverless Framework
      #   run: |
      #     npm install -g serverless
      #     serverless deploy
